service: adyen-payment-service

plugins:
  - serverless-offline
  # - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions:

  createSession:             #using this 
    handler: src/getpaymentpagelink.handler
    events:
      - http:
          path: /getpaymentpagelink
          method: post
          cors: true

  paymentDetails:                 
    handler: src/payment-details.handler
    events:
      - http:
          path: /payment-details
          method: post

  webhook:                     #using this
    handler: src/webhook.handler
    timeout: 30
    events:
      - http:
          path: /webhook
          method: post
          cors: true

  refundPayment:                 #using this
    refundPayment:
    handler: src/refund.handler
    events:
      - http:
          path: /refund
          method: post
          cors: true